#!/usr/bin/python3
"""This is a pascal triangle"""


def pascal_triangle(n):
    pascal_list = []
    
    if n <= 0:
        return pascal_list
    if n == 1:
        pascal_list[0] = [1]
        return pascal_list
    if n == 2:
        pascal_list[0] = [1]
        pascal_list[1] = [1, 1]
        return pascal_list
    if n > 2:
        pascal_list.append([1])
        pascal_list.append([1, 1])
        n_list = []
        n_list.append(1)
        n_list.append(1)
        for i in range(1, n - 2):
            for j, num in enumerate(pascal_list[n - 2]):
                k = j + 1
                if (j < n - 2) and (k < n - 2):
                    n_list[i] = num + pascal_list[k]
                    continue
                else:
                    i += 1
                    break
            pascal_list = append(n_list)
        return pascal_list
